social_impact_keywords = [
    "poverty alleviation",
    "environmental sustainability",
    "education access",
    "healthcare access",
    "social justice",
    "community development",
    "equality",
    "human rights",
    "empowerment",
    "sustainable development",
    "fair trade",
    "ethical",
    "inclusive growth",
    "economic development",
    "accessibility",
    "diversity",
    "inclusion",
    "social responsibility",
    "humanitarian",
    "philanthropy",
    "volunteerism",
    "socio-economic",
    "impact investing",
    "social enterprise",
    "non-profit",
    "sustainable livelihood",
    "gender equality",
    "women empowerment",
    "youth empowerment",
    "child welfare",
    "elderly care",
    "disaster relief",
    "mental health support",
    "peacebuilding",
    "conflict resolution",
    "racial justice",
    "environmental justice",
    "climate action",
    "biodiversity conservation",
    "renewable energy",
    "green technology",
    "water sanitation",
    "food security",
    "ethical sourcing",
    "worker rights",
    "community empowerment",
    "capacity building",
    "social cohesion",
    "civic engagement",
    "public health",
    "access to justice",
    "inclusive education",
    "equal opportunities",
    "social innovation",
    "ethical consumption",
    "human development",
    "global citizenship",
    "cultural preservation"
]