social_impact_keywords = [
    "poverty alleviation",
    "environmental sustainability",
    "education access",
    "healthcare access",
    "social justice",
    "community development",
    "equality",
    "human rights",
    "empowerment",
    "sustainable development",
    "fair trade",
    "ethical",
    "inclusive growth",
    "economic development",
    "accessibility",
    "diversity",
    "inclusion",
    "social responsibility",
    "humanitarian",
    "philanthropy",
    "volunteerism",
    "socio-economic",
    "impact investing",
    "social enterprise",
    "non-profit",
    "sustainable livelihood",
    "gender equality",
    "women empowerment",
    "youth empowerment",
    "child welfare",
    "elderly care",
    "disaster relief",
    "mental health support",
    "peacebuilding",
    "conflict resolution",
    "racial justice",
    "environmental justice",
    "climate action",
    "biodiversity conservation",
    "renewable energy",
    "green technology",
    "water sanitation",
    "food security",
    "ethical sourcing",
    "worker rights",
    "community empowerment",
    "capacity building",
    "social cohesion",
    "civic engagement",
    "public health",
    "access to justice",
    "inclusive education",
    "equal opportunities",
    "social innovation",
    "ethical consumption",
    "human development",
    "global citizenship",
    "cultural preservation",
    "digital inclusion",
    "tech for good",
    "digital literacy",
    "internet access",
    "cybersecurity",
    "digital rights",
    "tech equity",
    "data privacy",
    "e-waste management",
    "smart cities",
    "technology education",
    "online safety",
    "digital healthcare",
    "telemedicine",
    "remote learning",
    "digital inclusion",
    "tech entrepreneurship",
    "digital infrastructure",
    "ICT for development",
    "digital divide",
    "digital transformation",
    "internet of things (IoT)",
    "artificial intelligence (AI) for social good",
    "blockchain for social impact",
    "virtual reality (VR) for education",
    "augmented reality (AR) for accessibility",
    "crowdsourcing for humanitarian aid",
    "open data initiatives",
    "inclusive design",
    "technology for disaster response",
    "robotics for healthcare",
    "smart agriculture",
    "clean technology",
    "mobile health (mHealth)",
    "e-learning platforms",
    "online community building",
    "digital identity",
    "financial inclusion",
    "inclusive fintech",
    "tech-enabled social entrepreneurship"
]
